import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { withApiRoute } from '@/lib/apiRoute';
import { readJsonBody } from '@/lib/requestBody';
import { verifyTotpToken, generateRecoveryCodes } from '@/lib/mfa';
import { decryptSecret } from '@/lib/mfaCrypto';
import { logSensitiveAction } from '@/lib/auditLog';
import { z } from 'zod';

const schema = z.object({ token: z.string().min(6).max(10) });

// Story 15.32: confirms the secret generated by /api/auth/mfa/setup with a
// real code from the user's authenticator app before flipping mfaEnabled —
// proves they actually scanned the QR code and can produce valid codes,
// not just that a secret exists in the DB.
export const POST = withApiRoute(async (req: Request, { session }) => {
  const body   = await readJsonBody(req);
  const parsed = schema.safeParse(body);
  if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });

  const user = await prisma.user.findUnique({ where: { id: session.user.id } });
  if (!user || !user.mfaSecret) {
    return NextResponse.json({ error: 'Aucune configuration MFA en attente' }, { status: 400 });
  }
  if (user.mfaEnabled) {
    return NextResponse.json({ error: 'La double authentification est déjà activée' }, { status: 400 });
  }

  const secret = decryptSecret(user.mfaSecret);
  if (!verifyTotpToken(parsed.data.token, secret)) {
    return NextResponse.json({ error: 'Code invalide' }, { status: 400 });
  }

  const { raw, hashed } = await generateRecoveryCodes();
  await prisma.user.update({
    where: { id: user.id },
    data:  { mfaEnabled: true, mfaRecoveryCodes: hashed },
  });

  logSensitiveAction({ action: 'mfa_enabled', userId: user.id, email: user.email });

  return NextResponse.json({ data: { recoveryCodes: raw } });
}, { name: 'auth/mfa/enable:POST', rateLimit: true });
